// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvR32ZQ4RFjFP3b4aGWKzv-DGYLHXZ2l8',
    appId: '1:434748250856:android:0b9ae5ce81680ae038c75d',
    messagingSenderId: '434748250856',
    projectId: 'fraud-shield-ghana',
    storageBucket: 'fraud-shield-ghana.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqkjszMJk2EvHlTgYcy9FsaWrOfZXTWxk',
    appId: '1:434748250856:ios:3206f53459196a4638c75d',
    messagingSenderId: '434748250856',
    projectId: 'fraud-shield-ghana',
    storageBucket: 'fraud-shield-ghana.firebasestorage.app',
    iosClientId: '434748250856-c0l86g55b09695nudedmkqie7kotu2ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiQFhewyiPU9mgZXOmEOrZcCqyc_LhnSw',
    appId: '1:434748250856:web:aa04b7a5717f95ae38c75d',
    messagingSenderId: '434748250856',
    projectId: 'fraud-shield-ghana',
    authDomain: 'fraud-shield-ghana.firebaseapp.com',
    storageBucket: 'fraud-shield-ghana.firebasestorage.app',
  );

}